### PR TITLE
Updated to 1.19

### PR DESCRIPTION
**Pull request by Nitjsefnie**

### CODE REVIEW

**Comment by Nitjsefnie** [comment]
You can make a new branch and change the target branch yourself

**Comment by deirn** [comment]
Does this work with 1.19.2? I think it's better to build with 1.19.2 as that's the version that most people play.

**Comment by Nitjsefnie** [comment]
It does work with 1.19.2 as well, yes.

**Review by deirn — APPROVED** [review]

**Comment by deirn** [comment]
Thanks again.

**Pull request merged**
